[tool.ruff]
line-length = 180

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyright]
reportMissingTypeStubs = false

[tool.pylance]
typeCheckingMode = "basic"
reportMissingImports = false